# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
#Testing ( '-)-o=<|
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
#Reporting (...} \('-')-[..]
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
#Building *-('v')-*
- script: dotnet build src/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
