# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
#Testing <3
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
#Building *-('v')-*
- script: dotnet build src/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

#Deployment \(_' \)---( )))))
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Jumalan selän takana(a2b7df33-216c-4d62-8ec0-ca420e0bf182)'
    appType: 'webApp'
    WebAppName: 'christmascalendar'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'