<?xml version="1.0" encoding="UTF-8" ?>
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="html" doctype-public="XSLT-compat" omit-xml-declaration="yes" encoding="UTF-8" indent="yes" />
    <xsl:template match="/">
      <html>
        <head>
          <title>Test Result</title>
          <link rel="stylesheet" href="css/header.css" />
          <link rel="stylesheet" href="css/content.css" />
        </head>
        <body>
        <xsl:for-each select="assemblies/assembly">
        <div class="headers">
          <canvas class="graph" width="300px" height="300px"></canvas>
          <div>
          <xsl:choose>
            <xsl:when test="@total=@passed">
              <xsl:attribute name="class">header-passed</xsl:attribute>
            </xsl:when>
            <xsl:when test="@failed=0 and @errors=0">
              <xsl:attribute name="class">header-warning</xsl:attribute>
            </xsl:when>
            <xsl:otherwise>
              <xsl:attribute name="class">header-notpassed</xsl:attribute>
            </xsl:otherwise>
          </xsl:choose>
          <div class="header-title">Summary</div>
            <div class="header-grid">
            <div class="header-grid-label">Run Date</div>
            <div><xsl:value-of select="@run-date" /></div>
            <div class="header-grid-label">Run Time</div>
            <div><xsl:value-of select="@run-time" /></div>
            <div class="header-grid-label">Total</div>
            <div class="stat-total"><xsl:value-of select="@total" /></div>
            <div class="header-grid-label">Passed</div>
            <div class="stat-passed"><xsl:value-of select="@passed" /></div>
            <div class="header-grid-label">Failed</div>
            <div class="stat-failed"><xsl:value-of select="@failed" /></div>
            <div class="header-grid-label">Skipped</div>
            <div class="stat-skipped"><xsl:value-of select="@skipped" /></div>
            <div class="header-grid-label">Time</div>
            <div><xsl:value-of select="@time" />ms</div>
            <div class="header-grid-label">Errors</div>
            <div><xsl:value-of select="@errors" /></div>
            </div>
          </div>
          </div>
          <xsl:for-each select="collection">
          <div>
          <xsl:choose>
            <xsl:when test="@total=@passed">
              <xsl:attribute name="class">collection collection-passed</xsl:attribute>
            </xsl:when>
            <xsl:when test="@failed=0">
              <xsl:attribute name="class">collection collection-warning</xsl:attribute>
            </xsl:when>
            <xsl:otherwise>
              <xsl:attribute name="class">collection collection-notpassed</xsl:attribute>
            </xsl:otherwise>
          </xsl:choose>
          <div class="collection-header">
            <xsl:value-of select="@name"/>&#160;<strong>(<xsl:value-of select="@passed"/> / <xsl:value-of select="@total"/>)</strong>
            <small>&#160;&#160;<xsl:value-of select="@time"/>ms</small>
          </div>
            <xsl:for-each select="test">
            <div>
          <xsl:choose>
            <xsl:when test="@result='Pass'">
              <xsl:attribute name="class">collection-test collection-test-passed</xsl:attribute>
            </xsl:when>
            <xsl:when test="@result='Fail'">
              <xsl:attribute name="class">collection-test collection-test-notpassed</xsl:attribute>
            </xsl:when>
            <xsl:otherwise>
              <xsl:attribute name="class">collection-test collection-test-warning</xsl:attribute>
            </xsl:otherwise>
          </xsl:choose>
            <strong><xsl:value-of select="@result"/>
            </strong> in <xsl:value-of select="@method"/>&#160;<small>[ <xsl:value-of select="@time"/>ms ]</small><br/>
            <small class="test-target"><xsl:value-of select="@name"/></small>
            </div>
            </xsl:for-each>
          </div>
          </xsl:for-each>
        </xsl:for-each>
        <div class="footer">Generated by <a href="https://www.nuget.org/packages/XunitXml.TestLogger/">XunitXml.TestLogger</a>. XSL by <a href="https://github.com/rnielikki">github@rnielikki</a></div>
        <script src="js/graph.js"/>
        </body>
      </html>
    </xsl:template>
</xsl:transform>
